import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { TOOLS } from "../data/tools";
import { encodeStack } from "../utils/stackUrl";

export default function SharePanel({ open, onClose, selectedIds, accent = "#00f0ff" }) {
  const [copied, setCopied] = useState(null); // "link" | "markdown" | null

  const tools = selectedIds.map((id) => TOOLS.find((t) => t.id === id)).filter(Boolean);

  const copyLink = () => {
    const hash = encodeStack(selectedIds);
    const url = `${window.location.origin}${window.location.pathname}${hash}`;
    navigator.clipboard.writeText(url).then(() => {
      setCopied("link");
      setTimeout(() => setCopied(null), 2000);
    }).catch(() => {});
  };

  const copyMarkdown = () => {
    const lines = [
      "# AI Stack",
      "",
      "| Tool | Category | Free Tier | Link |",
      "|------|----------|-----------|------|",
      ...tools.map(
        (t) => `| ${t.name} | ${t.category} | ${t.free} | [${t.url}](https://${t.url}) |`
      ),
      "",
      `*Shared via [AIArsenal](https://aiarsenal.vercel.app)*`,
    ];
    navigator.clipboard.writeText(lines.join("\n")).then(() => {
      setCopied("markdown");
      setTimeout(() => setCopied(null), 2000);
    }).catch(() => {});
  };

  const downloadImage = () => {
    const canvas = document.createElement("canvas");
    const padding = 40;
    const rowH = 36;
    const w = 600;
    const h = padding * 2 + 60 + tools.length * rowH + 30;
    canvas.width = w * 2;
    canvas.height = h * 2;
    const ctx = canvas.getContext("2d");
    ctx.scale(2, 2);

    // Background
    ctx.fillStyle = "#0a0a0a";
    ctx.fillRect(0, 0, w, h);

    // Border
    ctx.strokeStyle = "#222";
    ctx.lineWidth = 1;
    ctx.strokeRect(0.5, 0.5, w - 1, h - 1);

    // Title
    ctx.fillStyle = accent;
    ctx.font = "bold 18px monospace";
    ctx.fillText("AI Stack", padding, padding + 20);

    // Subtitle
    ctx.fillStyle = "#666";
    ctx.font = "11px monospace";
    ctx.fillText(`${tools.length} tools — aiarsenal.vercel.app`, padding, padding + 40);

    // Divider
    ctx.strokeStyle = "#222";
    ctx.beginPath();
    ctx.moveTo(padding, padding + 54);
    ctx.lineTo(w - padding, padding + 54);
    ctx.stroke();

    // Tools
    tools.forEach((tool, i) => {
      const y = padding + 70 + i * rowH;
      ctx.fillStyle = "#e0e0e0";
      ctx.font = "bold 12px monospace";
      ctx.fillText(tool.name, padding, y);
      ctx.fillStyle = "#666";
      ctx.font = "10px monospace";
      ctx.fillText(tool.category, padding + 220, y);
    });

    // Watermark
    ctx.fillStyle = "#333";
    ctx.font = "9px monospace";
    ctx.fillText("Generated by AIArsenal", padding, h - 20);

    canvas.toBlob((blob) => {
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = "ai-stack.png";
      a.click();
      URL.revokeObjectURL(url);
    });
  };

  const btnStyle = {
    width: "100%", fontFamily: "monospace", fontSize: 11,
    background: "var(--surface-1)", color: "var(--text-secondary)",
    border: "1px solid var(--border-bright)",
    borderRadius: 8, padding: "11px 14px", cursor: "pointer",
    textAlign: "left", transition: "all 0.15s",
    marginBottom: 8,
  };

  return (
    <AnimatePresence>
      {open && (
        <>
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            style={{
              position: "fixed", inset: 0, zIndex: 60,
              background: "rgba(0,0,0,0.5)",
              backdropFilter: "blur(4px)",
            }}
          />

          <motion.div
            initial={{ opacity: 0, y: 20, scale: 0.95 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 20, scale: 0.95 }}
            transition={{ duration: 0.2, ease: [0.4, 0, 0.2, 1] }}
            style={{
              position: "fixed", top: "50%", left: "50%",
              transform: "translate(-50%, -50%)",
              zIndex: 61,
              width: 340, borderRadius: 14,
              background: "var(--surface-3)",
              backdropFilter: "blur(24px)",
              border: "1px solid var(--border-bright)",
              boxShadow: "0 16px 48px rgba(0,0,0,0.3)",
              overflow: "hidden",
            }}
          >
            {/* Header */}
            <div style={{
              display: "flex", alignItems: "center", justifyContent: "space-between",
              padding: "14px 16px", borderBottom: "1px solid var(--border)",
            }}>
              <span style={{
                fontFamily: "monospace", fontSize: 11, fontWeight: 600,
                color: accent, letterSpacing: 1.5,
              }}>
                SHARE STACK ({tools.length})
              </span>
              <button
                onClick={onClose}
                style={{
                  background: "none", border: "none", cursor: "pointer",
                  fontFamily: "monospace", fontSize: 14, color: "var(--text-faint)",
                  padding: "2px 6px", lineHeight: 1,
                }}
              >
                x
              </button>
            </div>

            <div style={{ padding: "16px" }}>
              <button
                onClick={copyLink}
                style={{
                  ...btnStyle,
                  color: copied === "link" ? "#00ff88" : "var(--text-secondary)",
                  borderColor: copied === "link" ? "#00ff8840" : "var(--border-bright)",
                }}
              >
                {copied === "link" ? "✓ Link Copied!" : "Copy Link"}
                <span style={{ display: "block", fontSize: 9, color: "var(--text-faint)", marginTop: 3 }}>
                  Shareable URL with your selected tools
                </span>
              </button>

              <button
                onClick={copyMarkdown}
                style={{
                  ...btnStyle,
                  color: copied === "markdown" ? "#00ff88" : "var(--text-secondary)",
                  borderColor: copied === "markdown" ? "#00ff8840" : "var(--border-bright)",
                }}
              >
                {copied === "markdown" ? "✓ Markdown Copied!" : "Copy as Markdown"}
                <span style={{ display: "block", fontSize: 9, color: "var(--text-faint)", marginTop: 3 }}>
                  Formatted table for docs or GitHub
                </span>
              </button>

              <button onClick={downloadImage} style={btnStyle}>
                Download as Image
                <span style={{ display: "block", fontSize: 9, color: "var(--text-faint)", marginTop: 3 }}>
                  PNG card for social sharing
                </span>
              </button>
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
}
